databases:
  - name: movie
    databaseName: movie_9844
    user: movie_9844_user

services:
  - type: web
    name: review
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false